overrides:
  - files:
      - "*.js"
    options:
      arrowParens: always
      singleQuote: true
      trailingComma: es5
      useTabs: true
  - files:
      - "*.json"
      - "*.md"
      - "*.yml"
    options:
      tabWidth: 2
